version: "3.9"

services:
  db:
    image: mysql
    container_name: database-apptasks
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=apptasks

  app:
    build: .
    container_name: apptasks
    restart: always
    command: yarn dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/apptasks
